version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # merge patches automatically
    update_type: "semver:patch"
    # Check the npm registry for updates every month
    schedule:
      interval: 'monthly'
